### ISSUE TITLE
Does route support regex?  Also how to match path input with Int or Long?

### ISSUE THREAD

**Issue by wpoosanguansit** [http4s/http4s_demo#10]
I am looking for an example of regex path and also how to constraint the url string to be of Long type for id.  The regex would be used to further check authorization and redirect to log user in.  Thank you for any pointer.

**Comment by bryce-anderson** [comment]
There currently isn't regex support for the core dsl. For the `Long` matching (among others), see [here](https://github.com/http4s/http4s/blob/master/dsl/src/main/scala/org/http4s/dsl/Path.scala#L165).

**Comment by wpoosanguansit** [comment]
Thanks for the pointer.
