### ISSUE TITLE
Can you show how to add Twirl to the mix?

### ISSUE THREAD

**Issue by wpoosanguansit** [http4s/http4s_demo#5]
This is closed as the following is added to the project

lazy val project = Project("http4s_demo", file(".")).enablePlugins(SbtTwirl)

sourceDirectories in (Compile, TwirlKeys.compileTemplates) := (unmanagedSourceDirectories in Compile).value

and everything is working correctly.

**Comment by bryce-anderson** [comment]
Hi @wpoosanguansit, glad you got it sorted. I still think it might be worth it to others to add a twirl example, so I might do that anyway.
