### ISSUE TITLE
How to setup SSL authentication to resources?

### ISSUE THREAD

**Issue by wpoosanguansit** [http4s/http4s_demo#7]
It would be useful to have sample of ssl enabled authentication to http services as well.  I have looked at Blaze http sample code but I am not quite sure if it would be the same a layer up.  Thanks for your help.

**Comment by bryce-anderson** [comment]
This is probably outside of the scope of the demo: its unlikely I'm going to get a signed SSL certificate for it.

Check out the [ServerBuilder](https://github.com/http4s/blaze/blob/0f6120edbb44271049c43bbf365606a7d9699cb1/examples/src/main/scala/org/http4s/blaze/examples/HttpServer.scala), in particular the [`SSLSupport`](https://github.com/http4s/http4s/blob/ec7c928183e5fe2bdc308f565e3ee1c09f561ae7/server/src/main/scala/org/http4s/server/ServerBuilder.scala#L58) trait. I believe the blaze, jetty, and possibly other backends support it. Assuming you've made you certificates right, all you need to do is set the right flags in the `withSSL` method.
