### ISSUE TITLE
How to decode json  using json4s?

### ISSUE THREAD

**Issue by wpoosanguansit** [http4s/http4s_demo#8]
I tried to switched out Argonaut and use json4s instead.  I get an error with decoder declaration.

from the call req.decode[Obj] in the method POST,

Error:(37, 57) not enough arguments for method jsonOf: (implicit reader: org.json4s.Reader[Obj])org.http4s.EntityDecoder[Obj].
Unspecified value parameter reader.
  implicit val objDecoder: EntityDecoder[Band] = jsonOf[Obj]
                                                        ^
How do I satisfy the implicit reader for the function call?  I checked up json4s doc and I do not see that being discussed.  So I am not sure how this is intended with http4s.  Thanks for your help.

**Comment by bryce-anderson** [comment]
`Reader` is defined [here](https://github.com/json4s/json4s/blob/9d4d75bef2f37f15e44073760c8f9077efb7505a/core/src/main/scala/org/json4s/JsonFormat.scala).

**Comment by wpoosanguansit** [comment]
Thanks.
